[package]

name = "spookytown"
version = "0.0.1"
authors = ["Douglas Campos <qmx@qmx.me>"]

[dependencies]

[dependencies.handlebars]
git = "https://github.com/sunng87/handlebars-rust"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs"

